all:
#	mips-linux-gnu-gcc socket_server_tcp.c server.c -lrt -muclibc -lpthread -o server
	gcc socket_server_tcp.c server.c -lrt -lpthread -o server
	gcc socket_client_tcp.c client.c -lrt -lpthread -o client
