#ifndef __AISP_GEKKO_INFERSDK_INCLUDE_VERSION_H__
#define __AISP_GEKKO_INFERSDK_INCLUDE_VERSION_H__

/*Generated by the compiler.  DO NOT EDIT!*/

#include "type.h"

/*mips toolchain*/
#define GCC_VERSION 7.2.0
#define GLIBC_VERSION 2.29
#define TOOLCHAIN_RELEASE_VERSION 5.1.9

/*gekko sdk*/
#define BUILD_TIME 20240327-15:52:15
#define PLATFORM mips
#define GEKKO_SDK_GIT_COMMIT 0ff72a5
#define GEKKO_SDK_VERSION 0.6.0-rc
#define GEKKO_SDK_VERSION_NUM 0x00060003
#define GEKKO_SDK_BUILD_INFO 20240327-15:52:15(7.2.0-r5.1.9 T41@mips@nna2)

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

GEKKO_API uint32_t gekko_get_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif //__AISP_GEKKO_INFERSDK_INCLUDE_VERSION_H__
