#ifndef _XCAM_GENERAL_H_
#define _XCAM_GENERAL_H_

#define XCAM_SUCCESS 0
#define XCAM_ERROR -1

#define XCAM_INVALID_CHANNEL -1
#define XCAM_INVALID_FLAG -1

#define CONFIG_EXISTENT_TAG 1
#define CONFIG_NON_EXISTENT_TAG 0

#define XCAM_STREAM_CHANNEL_0 0
#define XCAM_STREAM_CHANNEL_1 1
#define XCAM_STREAM_CHANNEL_3 3

#endif
